### ISSUE TITLE
get info event All day when i tap

### ISSUE THREAD

**Issue by gleyd** [zjfjack/JZCalendarWeekView#11]
hello, 
Is it possible to handle an event All day when I'm tapping on an event which is in frame All day

thanks you

**Comment by zjfjack** [comment]
Hi, Jean. Did you also send an email to me?
I tried not to make this library too complex.
For your case, I think you can only create an tap gesture to the all day view, then you can trigger the tap action.
Thanks a lot.

**Comment by gleyd** [comment]
Ok thanks you for your answer ^^, il will try to do this.



2018-07-05 11:37 GMT+02:00 Jeff Zhang <notifications@github.com>:
