### ISSUE TITLE
Longpress shadow

### ISSUE THREAD

**Issue by DanielBalsalobre** [zjfjack/JZCalendarWeekView#14]
Hello,

We want to make a shadow in selected cell on long-pressing in week/day view in add new mode but cannot see where and how to do this. This shadow must apply before trigger the long press event to indicate the user the hour that is selecting

Thanks.

**Comment by DanielBalsalobre** [comment]
https://youtu.be/e5FMJC-7mkU

We want to blur or apply shadow on the hour that user is selecting just after tap and before creating an event (during the long press).

Im trying to do this adding a gesture recognizer on tap event with cancelsTouchesInView set to false but cannot modify the background color of an empty hour, i will try to add a dummy element of collection view meanwhile. 

Thanks

**Comment by DanielBalsalobre** [comment]
In the youtube video im long pressing the hours to create a new event, but cannot see nothing that indicates the hour that im pressing.

**Comment by DanielBalsalobre** [comment]
Didn't work, tap and long press are totally different events. Are there a way to simulate "onmousedown" javascript event like in swift?

**Comment by DanielBalsalobre** [comment]
https://www.youtube.com/watch?v=U9j5Kk6PaIc

**Comment by zjfjack** [comment]
I am still quite confused about your description.
Have you implemented the JZLongPressViewDelegate, JZLongPressViewDataSource?

https://github.com/zjfjack/JZCalendarWeekView/blob/master/JZCalendarWeekView/JZLongPressWeekView.swift

**Comment by zjfjack** [comment]
Could you show me the design or the requirements what you want to do?

Thanks
