### ISSUE TITLE
iOS15 - Events weird movement after scrolling

### ISSUE THREAD

**Issue by HJafri256** [zjfjack/JZCalendarWeekView#142]
I have encountered an issue with iOS 15. 

The calendar's events are moving and changing their position by themselves scrolling a page. 

I am able to reproduce it with the test app.

Further my app integrating this calendar is removing events. They are still there as I can tap on them but they are not visible if you load the events and scroll back to the events. #138  also reported this.

Also the grid lines are blinking after a page is changed.

**Comment by tnt-agonm** [comment]
@HJafri256 How did you resolve the issue?  I have the same issue now using xCode 13
