### ISSUE TITLE
Long press types not checked

### ISSUE THREAD

**Issue by Fawxy** [zjfjack/JZCalendarWeekView#19]
I have set my available long press types to only `.addNew`, but when I long press on a cell as a move it still tries to perform the move long press, and as such the app is crashing. I can see that you check whether the long press types contain `.addNew`, but I don't see `.move` checked anywhere.

Should be fixed by #21

**Comment by zjfjack** [comment]
Thanks for your help.
I've already sent you the feedback through the pull requests section.
