### ISSUE TITLE
AllDay Event

### ISSUE THREAD

**Issue by yokurin** [zjfjack/JZCalendarWeekView#2]
Hi.
I want to set AllDay Event.
Do you have plan to support this ?

**Comment by yokurin** [comment]
Hi. Jeff.
Thank you for replay, and nice framework 😄 
I see. Also, I am not urgent. So I want you to try

Yes, I am looking for like your screenshot.

**Comment by zjfjack** [comment]
@yokurin Hi, Tsubasa.
All-day event feature is added~ 😎
