### ISSUE TITLE
Repeating Events

### ISSUE THREAD

**Issue by porollto** [zjfjack/JZCalendarWeekView#27]
Hi!
Thank you for sharing your work! I wonder if it is possible to create repeating Events (such as every Monday etc.)? Do you have any suggestions how this could be achieved?

Cheers!

**Comment by zjfjack** [comment]
For those repeating events, I think you can only generate dates and add them into the events list through the `JZWeekViewHelper.getIntraEventsByDate`.

Also, for the efficiency issue you shouldn't generate too many events into the events list. Maybe you can load few months and refresh them with `self.forceReload(reloadEvents: allEvents)` after date changing to some boundary.

Thanks

**Comment by porollto** [comment]
Thanks for your hint!
I've managed to create repeating Events by implementung `initDateDidChange(_ weekView: JZBaseWeekView, initDate: Date)`. Given the fact, that `initDate` is always the visible Date -1, I calculate the "next occurence" of the event by adding 7 days.
