### ISSUE TITLE
Feature Request: scrollTo(date: Date)

### ISSUE THREAD

**Issue by btxsqdr** [zjfjack/JZCalendarWeekView#28]
Hey there

So far, from what I know, it is relatively difficult to scroll to "today".

Think of the iOS Calendar and its "Today" button.

In order to achieve this, what I do is to setupCalendar(...) once again. That resets the calendar to the requested date. But this is ugly and happens instantly.

It would be better if we could scroll to a specific date. Is that possible already? Am I missing something? Or could you add it? Much appreciated.

With best regards

**Comment by zjfjack** [comment]
Hi, thanks for giving me so many suggestions.

For this one, you can use `func updateWeekView(to date: Date)` in JZBaseWeekView.
However, there is no scroll animation for this method, because you can update to any date you want.
