### ISSUE TITLE
Feature request: Show a full month

### ISSUE THREAD

**Issue by Zwaaan** [zjfjack/JZCalendarWeekView#32]
I've set the numOfDays = 30 so I can display a full month, the problem is that the first day to display is not set, I would like to show only November from 1:st to last. Is it possible?

**Comment by zjfjack** [comment]
Hi,

For this week view, it is mainly focused on 7 days or below that, if you are using month view, normally you should not display the event. Like Apple Calendar, you can try the JTAppleCalendar, which is better for month view.

**Comment by zjfjack** [comment]
I just close this issue, because I think the new feature might be what you want, if you have more questions, you can reopen it or maybe create a new one
