### ISSUE TITLE
Adding AM/PM Support

### ISSUE THREAD

**Issue by raguiar2** [zjfjack/JZCalendarWeekView#34]
Hello! 

First of all, thank you for the excellent work on this. One question I do have: I'm trying to add english locale support to show events in am/pm format on the longpress view and in the JZRowHeader. I can get the JZRowHeader to work by changing the dateformatter when overriding `viewForSupplementaryElementOfKind` in  a subclass of `JZLongPressWeekView`. However, I can't change the date format that shows up when you long press an event. I think it's the  `getTimeIgnoreSecondsFormat` method that is called. Is there any simple way to add am/pm support here? Or can we make some of the `private` methods `fileprivate` so I can edit the behavior of the long press in a subclass?

Thanks!

**Comment by zjfjack** [comment]
Hi

Is that okay for me to just simply change the private `updateTimeLabel` to public?

**Comment by raguiar2** [comment]
I think that could work.

**Comment by zjfjack** [comment]
I divided the original `updateTimeLabel ` into two methods, which are `updateTimeLabelText` and `updateTimeLabelPosition`. 

I made `updateTimeLabelText` be open, so you can override this method and change you label text.
I will only push to master, if you want to update pod, let me know. 

Thanks
