### ISSUE TITLE
Feature Request: Tap gesture recgonizer on events

### ISSUE THREAD

**Issue by raguiar2** [zjfjack/JZCalendarWeekView#35]
I'm not sure if I'm missing something, and I think https://github.com/zjfjack/JZCalendarWeekView/issues/11 may be related, but is there an easy way to recognize tap gestures (not long press ones) on events with this library? Could be helpful for a lot of use cases

**Comment by zjfjack** [comment]
You can simply implement the `didSelectItemAt` in UICollectionView
```swift

func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        let selectedEvent = getCurrentEvent(with: indexPath) as! DefaultEvent
        ToastUtil.toastMessageInTheMiddle(message: selectedEvent.title)
}
```

You can refer to the [DefaultWeekView](https://github.com/zjfjack/JZCalendarWeekView/blob/master/Example/JZCalendarWeekViewExample/Source/DefaultWeekView.swift)

Thanks

**Comment by raguiar2** [comment]
Yes, I was just going to close this after I saw that. Thanks for the quick response!

**Comment by zjfjack** [comment]
You are welcome, if you find any issue, let me know.

Thanks
