### ISSUE TITLE
how to make dynamic height for JZAllDayHeader ?

### ISSUE THREAD

**Issue by xxcombat** [zjfjack/JZCalendarWeekView#38]
hi!
tnx for this nice work!
how to make dynamic height for JZAllDayHeader ?
I need to see all the events from allDayevents without scrolling.

**Comment by zjfjack** [comment]
Hi, for this height,
I hard code it in JZBaseWeekView.swift 197 line
`let newAllDayHeader = flowLayout.defaultAllDayOneLineHeight * CGFloat(min(maxEventsCount, 2))`
You can simply change the code here or if you are using the Pods, then you can override the method.

Or maybe I can add one variable for you, what do you think? Do you have any idea about this variable?

Thanks

**Comment by xxcombat** [comment]
Thanks for the quick response.
I think variable is a good idea and will be useful to other developers.

**Comment by zjfjack** [comment]
I will add this variable as soon as possible, maybe during this weekend.
Will let you know soon.

Thanks

**Comment by zjfjack** [comment]
I've added one method called `getAllDayHeaderHeight` in JZBaseWeekView.
You can simply override this method to set preferred height.

Cheers~
