### ISSUE TITLE
Print statement in the code 

### ISSUE THREAD

**Issue by raguiar2** [zjfjack/JZCalendarWeekView#39]
I noticed there is the line `print(columnHeaderMinY, collectionView.contentSize.height)` in the JZWeekViewFlowLayout.swift. This seems to be printing a lot as I use the library. Is there any chance you could remove this?

Thanks!

**Comment by zjfjack** [comment]
Removed, thanks.
That was made by me when fixing the AllDayHeader scroll issue, and I forgot to delete this.
