### ISSUE TITLE
Fixed locale

### ISSUE THREAD

**Issue by mcubiro** [zjfjack/JZCalendarWeekView#43]
Hello

First of all thanks for great work! I've been using these library for a month ago and I've seen that calendar locale changes according to the system locale, but I can't find any way to set a fixed locale on week day names. It would be very nice if you could add a locale property to change the calendar language.

Thanks

**Comment by zjfjack** [comment]
Hi

In this case, I prefer you can customise your own column header and update yourself.
You can refer to the [HourRowHeader](https://github.com/zjfjack/JZCalendarWeekView/blob/master/Example/JZCalendarWeekViewExample/Source/CustomViews/HourRowHeader.swift), which is in my Example CustomViews.

After subclassing or creating your own columnHeader, you can change the locale in the dateFormatter to fix it. This part is quite easy and much better. If you have any further requirements, you only need change your own file.

Thanks

**Comment by mcubiro** [comment]
Thanks for your answer!
I'll do it this way, but I need you to make public the dateFormatter variable from JZColumnHeader so I can change the locale.

**Comment by zjfjack** [comment]
Already changed, cheers.
