### ISSUE TITLE
Load previous page sometimes doesn't work on 7days

### ISSUE THREAD

**Issue by kazuooooo** [zjfjack/JZCalendarWeekView#46]
Hi, thanks for making awesome library 😄 

I found a issue on sample app, which sometimes fail to load previous page on 7days and ScrollType Page Scroll.

I recorded movie below.

![img_0183 trim](https://user-images.githubusercontent.com/6919381/51542973-d4c7ad80-1e9f-11e9-8fb2-d874bfe5f073.gif)

and my environment is
* iPhone X(iOS 12.1.2)
* repo sample app
* my app settings

![img_a8b685442c0f-1](https://user-images.githubusercontent.com/6919381/51542501-bf05b880-1e9e-11e9-8033-87dbb5938045.jpeg)

I checked source code and found in loadPagePageScroll method,
currentOffset is not zero (0.333333333) on 7days and do nothing.
(other days are always 0 and loadPrevPage)

```
    private func loadPagePageScroll() {
        let maximumOffset = collectionView.contentSize.width - collectionView.frame.width
        // currentOffset sometimes 0.3333333333333333
        let currentOffset = collectionView.contentOffset.x

        if maximumOffset <= currentOffset {
            loadNextOrPrevPage(isNext: true)
        }
        if currentOffset <= 0 {
            loadNextOrPrevPage(isNext: false)
        }
    }
```

It works fine with dirty hack changing 

```
currentOffset <= 1
```

but it looks other original cause currentOffset is not zero on 7days only.

I couldn't find it by myself, and very glad to help or fix this bug 👍 

thanks,

**Comment by zjfjack** [comment]
Thanks for reporting this issue.
I find that this issue not only happened in 7days but also in other views.
I think some previous updates might cause this issue and I will fix it as soon as possible.

**Comment by kazuooooo** [comment]
@zjfjack 
Thank you so much!!

**Comment by zjfjack** [comment]
Hey, mate.

I know it is already 4 months later, but I finally resolve this issue with 0.7.0 version released. It is actually a quite major and difficult problem for the pagination.

You can check the release comment [here](https://github.com/zjfjack/JZCalendarWeekView/releases/tag/0.7.0).

If you have any other issue, let me know. I will close this issue.

Thanks
