### ISSUE TITLE
Update flow layout fails because of reload data absent

### ISSUE THREAD

**Issue by Koshub** [zjfjack/JZCalendarWeekView#47]
I am going to display a week in landscape orientation and a day in portrait. So I change layout to show 7 days and display header by adjusting its height. Before displaying a week I already have some items it data source so I resetup the component and while updating flow layout get fatal error because `forceReload` is dispatched async and could not be happened before layout update. In this case while preparing layout collection view still has some items while there are not any items set up.

Here is the code for setting up
```swift
    private func setupCalendarViewForDisplayingRange(_ range: DisplayingRange) {
        guard let calendarWeekView = calendarWeekView else { return }
        switch range {
        case .day:
            calendarWeekView.setupCalendar(numOfDays: 1,
                                           setDate: selectedDate,
                                           allEvents: [:],
                                           scrollType: .sectionScroll,
                                           firstDayOfWeek: .Monday)
            
            calendarWeekView.forceReload(reloadEvents: [:])
            calendarWeekView.updateWeekView(to: selectedDate)
            
            let layout = JZWeekViewFlowLayout(hourHeight: nil, rowHeaderWidth: nil, columnHeaderHeight: 0, hourGridDivision: nil)
            calendarWeekView.updateFlowLayout(layout)

        case .week:
            calendarWeekView.setupCalendar(numOfDays: 7,
                                           setDate: selectedDate,
                                           allEvents: [:],
                                           scrollType: .pageScroll,
                                           firstDayOfWeek: .Monday)
            
            calendarWeekView.forceReload(reloadEvents: [:])
            calendarWeekView.updateWeekView(to: selectedDate)
            
            let layout = JZWeekViewFlowLayout(hourHeight: nil, rowHeaderWidth: nil, columnHeaderHeight: 50, hourGridDivision: nil)
            calendarWeekView.updateFlowLayout(layout)
        }
    }
```
Here is an error:
<img width="1347" alt="screen shot 2019-02-07 at 5 33 50 pm" src="https://user-images.githubusercontent.com/7643346/52405743-94eb0200-2afe-11e9-9865-e41a0c453509.png">
Why are you data reload async?

**Comment by zjfjack** [comment]
Hi, I was quite busy for the last few days.
Have you solved this issue? 

I have one solution and you don't need setupCalendar every time, you can try
```swift
calendarWeekView.numOfDays = 7
calendarWeekView.refreshWeekView()
```

Also in this case, you could put `updateLayout` before refreshWeekView.
I haven't tried this solution yet. Could you try it first?

For the reason why I am using async, I cannot remember the actual reason.
If you are still confused with this issue, I will look into it, but it may take few weeks, quite busy these days.

**Comment by Koshub** [comment]
@zjfjack Thank you for response. I have already made my own component ))) The main problem here is async reload when collection view indexes is out of sync with data source. Anyway thank you again

**Comment by zjfjack** [comment]
Okay, I will look into this issue in the future. Thanks for your help.
Close it.

**Comment by fabien-ml** [comment]
Hello, i have actually the same problem with version 0.6.0 and above.
On orientation change i switch from a day view to a week view with this steps:
- change the numOfDays
- update the flowLayout
- forceReload or refreshWeekView

And i got the same error.

Note: v0.5.7 work fine.
