### ISSUE TITLE
When view is first shown, it is not correctly inset from the left, but after rotating it is.

### ISSUE THREAD

**Issue by ph1lb4** [zjfjack/JZCalendarWeekView#48]
When the view is first shown, there are no margins or inset from the left. However, after rotating the margins appear and the view looks fine. Is this a known issue?
![simulator screen shot - iphone xr - 2019-02-14 at 17 21 55](https://user-images.githubusercontent.com/6817230/52800912-1271bd80-307d-11e9-9791-6e474e4f2a25.png)
![simulator screen shot - iphone xr - 2019-02-14 at 17 22 00](https://user-images.githubusercontent.com/6817230/52800913-130a5400-307d-11e9-9a2c-bb54588b4968.png)

**Comment by zjfjack** [comment]
This is actually a mistake made by me. 
This inset is only for those devices with notch, like iPhone X, Xs. 
For normal device, there is no inset on the left. I will fix it soon, thanks

**Comment by zjfjack** [comment]
Fixed, thanks

**Comment by ph1lb4** [comment]
Great thanks 👍 Will you create a release with this for Cocoapods in the near future?

**Comment by zjfjack** [comment]
I will try to resolve your another issue, then I will create a release.

Thanks

**Comment by zjfjack** [comment]
Hi @ph1lb4,

I will release a new pod version with this update only because these few weeks I don't have enough time to deal with other issues.

As for #49 issue, I will try to go through it next week.

Thanks

**Comment by ph1lb4** [comment]
Works perfectly in the new release. Thanks.

**Comment by zjfjack** [comment]
Okay, for the other crash issue, I found the problem yesterday.
However, I need more time to change this part. Hopefully, I can finish it soon.
Thanks
