### ISSUE TITLE
tap action on week view

### ISSUE THREAD

**Issue by suvarnaratna** [zjfjack/JZCalendarWeekView#50]
Hi,

Thanks for the nice framework.

I want to add action to the week view whether event is available or not.

If there is no event on that particular date and time I want to create an event and event is there then I need to show event details.

Please help me to solve this.

Regards,
Suvarna Ratna A

**Comment by zjfjack** [comment]
Hi Suvarna,

If the event is there, you can simply implement the` UICollectionView` `didSelectCellAt` delegate function to show your event detail. You can refer to #35 issue.

However, if you want to tap the view and get the `Date` object, you can simply add a tap gesture to the collectionView in your subclass inherited from `JZBaseWeekView` or `JZLongPressWeekView` and in the selector function use this `JZBaseWeekView` funciton and get the date.

```Swift
func getDateForPoint(pointCollectionView: CGPoint) -> Date
```

Once you added the `TapGestureRecognizer`, in the selector function you can get the pointCollectionView by

```Swift
@objc func handleTap(sender: UITapGestureRecognizer) {
    let pointInCollectionView = sender.location(in: collectionView)
    let date = getDateForPoint(pointCollectionView: pointInCollectionView )
    // Do what you want with this date
}
```

Hope this can help you.

Thanks,
Jeff Zhang
