### ISSUE TITLE
Can I change header label colour and font size 

### ISSUE THREAD

**Issue by RanjeetStiga** [zjfjack/JZCalendarWeekView#53]
I want customise the header of calender like change font colour of toady date and header height.

**Comment by zjfjack** [comment]
Absolutely. You can refer to the example project code. [CustomViews](https://github.com/zjfjack/JZCalendarWeekView/tree/master/Example/JZCalendarWeekViewExample/Source/CustomViews)

**Comment by RanjeetStiga** [comment]
But in this example Header custom class not available

**Comment by zjfjack** [comment]
This is the same idea for both row header and column header. Just create your own column header as what I did in HourRowHeader, and change your color and font. If you want to change the height, you have to do it in your `ViewController` like:

```swift
calendarWeekView.updateFlowLayout(JZWeekViewFlowLayout(hourHeight: 50, rowHeaderWidth: 50, columnHeaderHeight: 50, hourGridDivision: JZHourGridDivision.noneDiv))
```

**Comment by RanjeetStiga** [comment]
Thanks
