### ISSUE TITLE
Bug: Cell rendering

### ISSUE THREAD

**Issue by btxsqdr** [zjfjack/JZCalendarWeekView#54]
Hey Jeff

I've found an issue that might be important. Could you have a look at it? Thank you. @zjfjack 

These 3 events are from the same day, yet the 3rd appears on the next day:

![cal1](https://user-images.githubusercontent.com/1353114/55623189-8dfd0a80-57a2-11e9-9554-4d9fb653715d.png)

Here's how to reproduce:

For simplification, use your example code and alter AllDayViewModel like so

```
class AllDayViewModel: NSObject {

    private let firstDate = Date()
    private let secondDate = Date().add(component: .minute, value: 22)
    private let thirdDate = Date().add(component: .minute, value: 27)

    lazy var events = [
        AllDayEvent(id: "0", title: "One", startDate: firstDate, endDate: firstDate.add(component: .minute, value: 30), location: "Melbourne", isAllDay: false),

        AllDayEvent(id: "1", title: "Two", startDate: secondDate, endDate: secondDate.add(component: .minute, value: 30), location: "Sydney", isAllDay: false),

        AllDayEvent(id: "2", title: "Three", startDate: thirdDate, endDate: thirdDate.add(component: .minute, value: 30), location: "Tasmania", isAllDay: false)
    ]

    lazy var eventsByDate = JZWeekViewHelper.getIntraEventsByDate(originalEvents: events)

    var currentSelectedData: OptionsSelectedData!

}
```

It means that 3 events that are very close should be rendered on the same day.

Thank you very much! :)

**Comment by btxsqdr** [comment]
@zjfjack May I ask for a status update? Are you working on it or shall I try to provide a pull request with a hopefully reasonable solution?

**Comment by zjfjack** [comment]
You can do a pr for reference, thanks for your effort. I don't work on
weekdays usually.

**Comment by btxsqdr** [comment]
Hey @zjfjack. Could you either give me branch and pull request access, or adjust this code line yourself?

JZWeekViewFlowLayout, line 541

From
`for currentY in stride(from: minY, to: maxY, by: 1) {`

To
`for currentY in stride(from: minY, to: maxY, by: 0.1) {`

Because if minY/maxY diff is < 1, stride by 1 will skip some items if too close, therefore 0.1.

**Comment by btxsqdr** [comment]
@zjfjack see pr https://github.com/zjfjack/JZCalendarWeekView/pull/65

**Comment by zjfjack** [comment]
Hi @btxsqdr 

Thanks for your help, I finally have some time to look into this issue.

Your solution can definitely solve this issue, but I am thinking about efficiency. The original solution is not efficient already. If you change it to 0.1, then it will become worse.

Then, I find a better solution which I will show it here with the algorithm link. [Maximum number of overlapping intervals](http://www.zrzahid.com/maximum-number-of-overlapping-intervals/)

I will finish the solution in Swift and let you know soon.

Thanks

**Comment by zjfjack** [comment]
Pushed new commit, if you have any other questions, let me know. Thanks
