### ISSUE TITLE
change hour to half an hour

### ISSUE THREAD

**Issue by mohit2305** [zjfjack/JZCalendarWeekView#58]
how can we change it to half an hour settings

**Comment by zjfjack** [comment]
what do you mean? Hour interval change to half an hour? Not supported yet, but you can add `hourGridDivision` to `minutes_30 `

**Comment by mohit2305** [comment]
Sure will do thanks for your quick response

**Comment by YahyaBagia** [comment]
@zjfjack  how do I change `hourGridDivision`'s value to `minutes_30` ? Could you please share example code here?
