### ISSUE TITLE
Month view

### ISSUE THREAD

**Issue by mohit2305** [zjfjack/JZCalendarWeekView#59]
It is limited to days or it can be change to Month view

**Comment by zjfjack** [comment]
nah, month view is not supported, because it is a weekView project. If you want to do month view, you can check [JTAppleCalendar](https://github.com/patchthecode/JTAppleCalendar)

**Comment by mohit2305** [comment]
No worries I need to then work out for solution as I need month and week
view both.

Thanks for your quick reply , have a great day !!
