### ISSUE TITLE
Localize "all-day" String

### ISSUE THREAD

**Issue by DanielBalsalobre** [zjfjack/JZCalendarWeekView#6]
Hello,

First, VERY GOOD JOB BRO!

I need to localize this String but cannot see how to access lblTitle of JZAllDayCorner from my project.

Thanks

**Comment by zjfjack** [comment]
Hi, Daniel.
I will fix this issue and let you know soon. Thanks

**Comment by zjfjack** [comment]
Hi, Daniel.

I find a way that you can achieve this easily. Also, if you want to change any other SupplementaryView or DecorationView, you can use this method or refer to the [customWeekView](../tree/master/Example/JZCalendarWeekViewExample/Source/CustomViews/CustomWeekView.swift).

Firstly, creating (or subclass) your own AllDayCorner (DecorationView), and override `setupUI` class or create your own one. Make sure you set the correct constraints for the lblTitle to support iPhone X and bottom divider like what I have done in JZAllDayCorner, if you want to create your own AllDayCorner class.

```Swift
// Sample of subclassing
override func setupUI() {
    super.setupUI()
    // Do your localization here
    lblTitle.text = LocalizedString
}
```
Secondly, just register this class in your own weekView `registerViewClasses`(like I did in [customWeekView](../tree/master/Example/JZCalendarWeekViewExample/Source/CustomViews/CustomWeekView.swift) for the `BlackGridLine`)

```Swift
self.flowLayout.register(YourAllDayClass.self, forDecorationViewOfKind: JZDecorationViewKinds.allDayCorner)
```

By the way, if you have any other better solutions, please let me know, we can discuss about this and try to improve this project.

Thanks a lot.

**Comment by DanielBalsalobre** [comment]
Thanks a lot
