### ISSUE TITLE
Tap Action on a free cell

### ISSUE THREAD

**Issue by gharary** [zjfjack/JZCalendarWeekView#61]
Hi, First of all, thanks for your great repo, I have tried couples of other repos, and all of them were a waste of time till I've found yours.
However, I'm trying to implement a calendar which shows the user four weeks, and it's days so the user can choose which times on which days is he/she free by tapping on cell hours.
The problem is that I don't know where to implement tap gesture.

As you mentioned in #50 in a collectionView subclass inherited from JZBaseWeekView, but In your Example project, I haven't found did you use JZBaseWeekView.
Could you please help me with that?

Appreciate that.

**Comment by zjfjack** [comment]
Hi,

`LongPressWeekView` in example project is from `JZLongPressWeekView` which is inherited from `JZBaseWeekView`. If you want to add tap gesture without long press, you only need to implement the solution from #50 to the collectionView in your own `JZBaseWeekView` (like `DefaultWeekView`).

Thanks

**Comment by gharary** [comment]
Thanks for your quick reply,
I've implemented your way. However I'm unable to get the indexPath of the cell which user is tapping, I've tried a couple of ways, but I get errors.
For example :
        let pointInCollectionView = sender.location(in: self.collectionView)
        let indexPath = self.collectionView.indexPathForItem(at: pointInCollectionView)

I'm going to change the background color of that cell to show the user that it's been selected or not, 
after that storing the hole date and times (hourly) which the user has selected!

**Comment by gharary** [comment]
Any Solution for that?

**Comment by zjfjack** [comment]
Hi,

I am still confused with your question.

My solution in #50 is allowed you to handle tap gesture event on collectionView instead of cell. If you want to do tap gesture on cell itself, you can just simply implement `UICollectionView` delegate method `didSelectItemAt`.

If you want to change the background color, it depends (because I am not clear about your question)

- Tap on collectionView without cells: Add a cell to cover the position you tap
- Tap on a cell: Simply change the cell background

Maybe you can tell me about your design, a picture will be much easier.

Thanks

**Comment by gharary** [comment]
import JZCalendarWeekView

class WeekViewClass: JZBaseWeekView {
    
    override func registerViewClasses() {
        super.registerViewClasses()
        
        //Register CollectionViewCell
        self.collectionView.register(EventCell.self, forCellWithReuseIdentifier: "EventCell")
        
        
        //Register Class
        let tap = UITapGestureRecognizer(target: self, action: #selector(handleTap(sender:)))
        self.collectionView.addGestureRecognizer(tap)
        
        
    }
    
    override func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let date = flowLayout.dateForColumnHeader(at: indexPath)
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "EventCell", for: indexPath) as! EventCell
        
        return cell
    }
    
    
    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        let cell = self.collectionView.cellForItem(at: indexPath)
        cell?.backgroundColor = .red
        
    }
    @objc func handleTap(sender: UITapGestureRecognizer) {
        let point = sender.location(in: self.collectionView)
        let index = self.collectionView.indexPathForItem(at: point)
        
        print(index) //Print nil
        
        print("Item Clicked!")
    }
    
    @objc func handleCellTap(sender: UITapGestureRecognizer) {
        
    }
}

**Comment by gharary** [comment]
![Screen Recording 2019-04-28 at 12 24 19 PM](https://user-images.githubusercontent.com/16289125/56860906-cc0bd980-69b0-11e9-993d-a9d0744dba7e.gif)

**Comment by zjfjack** [comment]
All the grids in the gif are UICollectionViewCells, am I right?

It's really weird because cells should be called when tapped with delegate method 'didSelectItemAt' which is predefined by iOS. It seems that handleTap is not required in this case, because you are using UICollectionViewCell.

Could you check why the 'didSelectItemAt' method not called?

**Comment by gharary** [comment]
Yeap, Those are all cells.
I've checked your repo and also #50 and #35. The method you mentioned working just for events and I think `didSelectItemAt` just get called when user taps on Events.
However I'm going to implement it for empty cells.

**Comment by zjfjack** [comment]
Hmm that's really weird.

Is it maybe because you added the tapGesture? Refer to this questions https://stackoverflow.com/questions/39780373/didselectitemat-not-being-called

**Comment by gharary** [comment]
I've deleted all tapGesture codes and checked it out. No difference. 
The didSelectItemAt only called when clicking on events, not free cells.

**Comment by gharary** [comment]
Take a look at this gif, I've added two line into your example project in `didSelectItemAt` method and it's the result.

`let cell = collectionView.cellForItem(at: indexPath)
        if cell!.isSelected {
            cell?.backgroundColor = .red
        }`


![Screen Recording 2019-04-29 at 6 47 38 PM](https://user-images.githubusercontent.com/16289125/56902525-b7fad180-6aaf-11e9-9121-171678876a14.gif)

**Comment by zjfjack** [comment]
Is it what you want?

**Comment by gharary** [comment]
Nop, 
I want to change the color of free cells, not the ones with events.

**Comment by zjfjack** [comment]
Okay, I finally got your idea which is updating the empty part. For
collectionView coloring, it is not achieved yet. My suggestion for you is
creating all  events cells in collectionView each grid and do the
didSelectItemAt because of the design image you sent to me. Is this okay?

**Comment by gharary** [comment]
Actually my goal is :
at first users sees a completely empty time grid and then he can choose the times he/she wants by selecting cells, and then the selected cells get their colored changed.
after that I store the selected times by user, and send them to my backend for further processing.

**Comment by gharary** [comment]
Maybe I should create events for every hours of the grid, and then the user can select them and I can get those events by `didSelectItem` method.
Is that right?

**Comment by zjfjack** [comment]
Yes, although the performance will be influenced, it is currently a right
solution.

**Comment by gharary** [comment]
how can I do that with your Repo, a little help would be appreciate really.

**Comment by zjfjack** [comment]
Create 24 events for everyday each hour with duration one hour. For the
corner radius and margin, you can achieve it with your own
UICollectionViewCell. Regarding the four corners cells, you can set the
corner radius for required angle with IndexPath check in CellForItemAt to
configure the cell.

For customised cell, you can go through the example project, it will help.

**Comment by gharary** [comment]
Thanks for ur great support.
going to implement this way.
Thanks

**Comment by PoojaSoftRadix** [comment]
Hi @gharary 
I am also facing same issue on Tap Action on a free cell
Could you please share code 
Thanks
