### ISSUE TITLE
SDK not support for Xocde 10.2.1 Swift 5

### ISSUE THREAD

**Issue by RanjeetStiga** [zjfjack/JZCalendarWeekView#63]
Hi ,
 I am getting "The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions" in JZWeekViewFlowLayout file when run in Xcode 10.2.1.

**Comment by RanjeetStiga** [comment]
> Hi ,
> I am getting "The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions" in JZWeekViewFlowLayout file when run in Xcode 10.2.1.

Hi Please update on this .

**Comment by gharary** [comment]
You can do this:
`let columnHeight = columnHeaderHeight + hourHeight * 24
        let columnMargin = contentsMargin.top + contentsMargin.bottom + allDayHeaderHeight
        return  columnHeight + columnMargin`
Worked for me.

**Comment by zjfjack** [comment]
I've updated the pod version to resolve this issue and cell rendering issue, please update to latest pod version or pull the latest code from master.
