### ISSUE TITLE
Q: please which file (row) is for header day and week day?

### ISSUE THREAD

**Issue by PMA22** [zjfjack/JZCalendarWeekView#68]
I want empty header. Without day and weekday. I have only one day calendar, header width = 0, but number of day and weekday is still on screen.

calendarWeekView.updateFlowLayout(JZWeekViewFlowLayout(hourHeight: 40, rowHeaderWidth: 50, columnHeaderHeight: 0 , hourGridDivision: JZHourGridDivision.noneDiv))

<img width="377" alt="Snímek obrazovky 2019-05-09 v 9 59 23" src="https://user-images.githubusercontent.com/46519631/57437051-4524ef80-7241-11e9-82fb-2cb3a3791a85.png">

**Comment by zjfjack** [comment]
Okay, it seems I didn't handle this situation. I will fix it later and let you know soon.

**Comment by zjfjack** [comment]
If you are using `JZColumnHeader`, I've fixed it now.

If you want to use your customised header, you can just simply add `self.clipsToBounds = true` in your column header view.

**Comment by PMA22** [comment]
Hello,

thank you very much for quick response. 

Is there some options for displayed time. If I want time  from 10 a.m. to 3 p.m. for example?

Thank you

Have a nice day
P.M.

petra@manticova.cz
