### ISSUE TITLE
Long press date offset

### ISSUE THREAD

**Issue by DanielBalsalobre** [zjfjack/JZCalendarWeekView#7]
Hello,

I faced to a possible date offset bug in one hour, if i long press to create event between 1:00 and 2:00 the start date was 0:00 and end date 1:00 and so on. Only first hour (0:00 to 1:00) was fine.

I have achieved a solution removing this offset (note the stroked part): 

let adjustedY = yCollectionView ~~- flowLayout.columnHeaderHeight~~ - flowLayout.contentsMargin.top - flowLayout.allDayHeaderHeight

Probably this issue is caused because i have customised views, but modifying longPressTopMarginY didn't work as expected.

You can close this issue.
Thanks!

**Comment by zjfjack** [comment]
Hi, Daniel.
You can check this issue again when you fix your issues, if this issue still exists, I will help you to fix this bug. Thanks
