### ISSUE TITLE
how can I change EventTimeView background color ?

### ISSUE THREAD

**Issue by MourinhoLove** [zjfjack/JZCalendarWeekView#74]
just  change overlay to grid to view's background color.

**Comment by zjfjack** [comment]
which view? Do you mean the `UICollectionViewCell` or the `UICollectionView` itself background for each grid?

**Comment by MourinhoLove** [comment]
> 哪个观点？你的意思是每个网格的背景`UICollectionViewCell`或`UICollectionView`自身背景？

just blue color view. It is overlay to grid.

**Comment by MourinhoLove** [comment]
> which view? Do you mean the `UICollectionViewCell` or the `UICollectionView` itself background for each grid?

just blue color view. It is overlay to grid.

**Comment by MourinhoLove** [comment]
> which view? Do you mean the `UICollectionViewCell` or the `UICollectionView` itself background for each grid?

I fix this. but how can I update Events?

**Comment by zjfjack** [comment]
Do you want to update the events for the `UICollectionViewCell`?

你这英文我是真看不懂，说不清楚用中文吧，两个人尬来尬去的。你想做啥？你是要改事件的UI吗？参考example项目里的 `EventCell`，你重新建一个你想要的`UICollectionViewCell`,然后写就行了，更新其实就`cellForItemAt`里面更新就好了。

**Comment by MourinhoLove** [comment]
> Do you want to update the events for the `UICollectionViewCell`?
> 
> 你这英文我是真看不懂，说不清楚用中文吧，两个人尬来尬去的。你想做啥？你是要改事件的UI吗？参考example项目里的 `EventCell`，你重新建一个你想要的`UICollectionViewCell`,然后写你想要的UI就行了，更新其实就`cellForItemAt`里面dequeue，然后configureCell就好了。
> 
> 可以参考`DefaultWeekView.swift` 和 `EventCell.swift`

原来老哥会中文，谢谢老哥的解答。嗯我已经自定义Cell。更新的话我调用collectionView.reloadData就行了吧

**Comment by zjfjack** [comment]
不用谢～
你可以用，不过我定义了`forceReload`方法，你可以试试`reloadData`，不行就用`forceReload`
