### ISSUE TITLE
Interaction with AllDay event

### ISSUE THREAD

**Issue by gosdragon** [zjfjack/JZCalendarWeekView#75]
Hi

First of all, thanks for the framework.

I'm trying to do actions when all day event is tapped, but no method is called unlike other event. How can I intercept this action?

Thank you so much

**Comment by zjfjack** [comment]
Because all day events are implemented by `UIView`. You can simply implement it by adding a tap gesture.

**Comment by gosdragon** [comment]
Yes, this is what I did, I just wanted to know if there was something done.

Thanks for the help 👍
