### ISSUE TITLE
How to pass an event to another ViewController

### ISSUE THREAD

**Issue by gharary** [zjfjack/JZCalendarWeekView#81]
I'm developing a calendar to show the user some events, and then the user selects some of them.
After that, I want to send selected events to another VC.
Generating events are on DefaultViewController of your code, and selection of the user is triggering on DefaultWeekView. 
How can send the events to another VC?

**Comment by zjfjack** [comment]
Set a delegate in DefaultWeekView and implement this delegate in VC.

Are you new to iOS?
