### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [zjfjack/JZCalendarWeekView#9]
Good day @zjfjack  I am a graphic designer and i want to contribute to your nice project by doing a logo for it. I will be doing it for free as my gift to the project. I need your permission first before I begin my design. Hoping for a positive feedback. Thanks and best regards! - Tobaloidee

**Comment by zjfjack** [comment]
Hi, Tobaloidee.
I am very glad that you can make a logo for me.
Really appreciate, Thanks a lot

**Comment by Tobaloidee** [comment]
I will start my design and show you here when done @zjfjack  :)

**Comment by zjfjack** [comment]
Hi Tobaloidee.
I really like this design, but only one thing not good.

<img width="115" alt="screen shot 2018-07-03 at 11 31 22 am" src="https://user-images.githubusercontent.com/4811838/42193925-bb6b244c-7eb4-11e8-8948-15bd1c8234cc.png">

For the mouse cursor you see in the gif is from the phone simulator and used to show I did the drag action in some position. However, this library is made for mobile (iOS), which means the cursor and the outside circle will never be shown. Could you make few changes to this part?

Btw, I love the light background.

Thanks a lot

**Comment by Tobaloidee** [comment]
Actually Sir i thought of that cursor to be a part of the app..here's my initial design actualy

![pres2-01](https://user-images.githubusercontent.com/36028424/42194383-4f52eec4-7ea6-11e8-8e50-21a2d33ce840.png)

**Comment by zjfjack** [comment]
Hi, @Tobaloidee 
I prefer not to use the cursor one, would you like to make the top-right corner empty or put a date on it or some characters? Thx

**Comment by Tobaloidee** [comment]
Hi Sir, after trying some characters it is much better empty..you are correct! 

![pres3-01](https://user-images.githubusercontent.com/36028424/42303506-45cf38ee-8054-11e8-89ac-557cab3f48a3.png)

ill make a PR and upload it if its good to go

**Comment by zjfjack** [comment]
Yeah, I love this~ Thanks a lot!

**Comment by Tobaloidee** [comment]
Here's the PR #10 Sir, Thanks! - Tobaloidee

**Comment by zjfjack** [comment]
@Tobaloidee Really like this design, thanks a lot!

**Comment by Tobaloidee** [comment]
You are very much welcome @zjfjack :)

**Comment by zjfjack** [comment]
@Tobaloidee Thank you!! Really appreciate your work!!

**Comment by Tobaloidee** [comment]
The pleasure is mine! Thanks again Sir..👌
