### ISSUE TITLE
How can I show different type of events with different colors?

### ISSUE THREAD

**Issue by NeenaMishra12** [zjfjack/JZCalendarWeekView#90]
Hi @zjfjack ,
Thank you for the awesome library. In my app, I am having different type of events and I want user to identify them by using different colors. How can I achieve this? 
Can you please help me with it?

**Comment by zjfjack** [comment]
Hi,

You can simply define different types of `UICollectionViewCell` and configure them in `UICollectionViewDelegate` method `cellForItemAt`

**Comment by NeenaMishra12** [comment]
Fixed it. Thanks
