### ISSUE TITLE
How to programatically remove/add an event in weekCalendar

### ISSUE THREAD

**Issue by Nikoloutsos** [zjfjack/JZCalendarWeekView#91]
Hey I have a question, excuse me if this is a trivial question but I am a beginner,

Is there any way to remove an eventCell from the weekCalendar programatically?
Also how to add a new event?? Can we only add all our events only at the start (In the constructor)?

Thank you for this amazing library!

**Comment by Nikoloutsos** [comment]
I found a solution to this.
I used the following method and altering my list of events as I wanted

`calendarWeekView.forceReload(reloadEvents:)`

**Comment by zjfjack** [comment]
Actually you can use `UICollectionView` delegate method `deleteItemsAt` and `insertItemsAt` to remove and add event. You can still force reload but no need for that.

**Comment by Nikoloutsos** [comment]
Thank you, it works like a charm!
