### ISSUE TITLE
Use of JZColumnHeader to modify header font and color

### ISSUE THREAD

**Issue by malignois** [zjfjack/JZCalendarWeekView#96]
Hello, 

I try to use JZColumnHeader to modify the font and the color of the header, I followed your explanations to use it like JZRowHeader but I fail.

I succeed with JZRowHeader overriding  setupBasic function to modify lblTime but I don't know how to do with JZColumnHeader because this function doesn't exist. 
I tried overriding init(frame: CGRect) but then in my JZBaseWeekView class, when i do :

```
if kind == JZSupplementaryViewKinds.columnHeader {
            let columnHeader = collectionView.dequeueReusableSupplementaryView(ofKind: kind, withReuseIdentifier: ColumnHeader.className, for: indexPath) as! ColumnHeader
            columnHeader.updateView(date: flowLayout.dateForColumnHeader(at: indexPath))
            return columnHeader
        }
```

It doesn't apply changes on my header view.

Can you please help me ?

**Comment by zjfjack** [comment]
Have you tried to follow the `CustomWeekView.swift`?

You should register this class first and implement it in `viewForSupplementaryElementOfKind` before `super`

**Comment by malignois** [comment]
Thank you, it works now.
